import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("README implements the approved executive overview", async () => {
  const readme = await readFile("README.md", "utf8");

  assert.match(readme, /<div align="center">/);
  assert.match(readme, /^# Vincenzo Di Mauro/m);
  assert.match(readme, /^## Backend Engineer & Software Architect/m);
  assert.equal(readme.match(/<td width="33%" valign="top">/g)?.length, 3);
  assert.match(readme, /<h3>01 · Backend<\/h3>/);
  assert.match(readme, /<h3>02 · Integrazioni &amp; realtime<\/h3>/);
  assert.match(readme, /<h3>03 · Produzione<\/h3>/);
  assert.match(readme, /^## Stack essenziale/m);
  assert.match(readme, /<code>TypeScript<\/code>/);
  assert.match(readme, /^## Competenze validate sui progetti/m);
  assert.match(readme, /<h3>Avanzato<\/h3>/);
  assert.match(readme, /Backend architecture/);
  assert.match(readme, /TypeScript \/ Node\.js/);
  assert.match(readme, /Python/);
  assert.match(readme, /PostgreSQL \/ SQL/);
  assert.match(readme, /Realtime &amp; integrazioni/);
  assert.match(readme, /<h3>Intermedio–avanzato<\/h3>/);
  assert.match(readme, /DevOps &amp; osservabilità/);
  assert.match(readme, /AI applicata \/ LLM/);
  assert.match(readme, /<h3>Complementari · Intermedio<\/h3>/);
  assert.match(readme, /React \/ TypeScript/);
  assert.match(readme, /<strong>Go<\/strong>/);
  assert.match(readme, /PHP \/ MySQL/);
  assert.match(readme, /I repository restano riservati/);
  assert.doesNotMatch(readme, /Tyche|BetYourScore|Risk_LLM|SisalGameEngine|DevShare|HandiMap/);
  assert.doesNotMatch(readme, /\b\d{1,3}%\b/);
  assert.match(readme, /^## Dal requisito alla produzione/m);
  assert.match(readme, /^## Attività GitHub pubblica/m);
  assert.match(readme, /> \*\*Hai un sistema backend complesso da progettare o evolvere\?\*\*/);
  assert.match(readme, /\.\/profile\/stats\.svg/);
  assert.match(readme, /https:\/\/vincodelab\.com/);
  assert.match(readme, /https:\/\/www\.linkedin\.com\/in\/vdmweb\//);
  assert.match(readme, /mailto:info@vincodelab\.com/);
  assert.doesNotMatch(readme, /shields\.io|visitor|trophy|badge/i);
});